# Generated by Django 4.1.5 on 2023-01-10 18:37

import api.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", api.fields.TokenAutorizateField(max_length=33, unique=True)),
                ("telegram_id", models.CharField(max_length=120)),
                ("data_create", models.DateField(auto_now=True)),
                ("date_end", models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.token"
            ),
        ),
    ]
